# Generated by Django 4.0.3 on 2022-03-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField(blank=True, null=True)),
                ('trade_code', models.CharField(blank=True, max_length=50, null=True)),
                ('high', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
