# Generated by Django 4.0.3 on 2022-03-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_high'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
