# Generated by Django 4.0.3 on 2022-03-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_close_customer_low_customer_open_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('trade_code', models.CharField(blank=True, max_length=50, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('open', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
